name: Test AMD64 Docker Image Fully

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-amd64:
    runs-on: ubuntu-latest   # Real AMD64 VM

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Mortaza@348
          MYSQL_DATABASE: face_recognition_attendance
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        ports:
          - 3306:3306
        volumes:
          - ${{ github.workspace }}/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull AMD64 Docker image
        run: docker pull mortaza77/database:amd64

      - name: Run FastAPI container
        run: |
          docker run -d --name test-app \
            --link mysql:mysql \
            -e MYSQL_HOST=mysql \
            -e MYSQL_PORT=3306 \
            -e MYSQL_DATABASE=face_recognition_attendance \
            -e MYSQL_USER=root \
            -e MYSQL_PASSWORD=Mortaza@348 \
            -p 8001:8001 \
            mortaza77/database:amd64

      - name: Wait for FastAPI startup
        run: sleep 15

      - name: Test /health endpoint
        run: |
          docker exec test-app python -c "import requests; r = requests.get('http://localhost:8001/health'); print('Status:', r.status_code); assert r.status_code == 200"

      - name: Stop FastAPI container
        run: docker stop test-app
